spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/thathinh}
spring.data.mongodb.database=${MONGODB_DATABASE:thathinhdb}
spring.data.mongodb.auto-index-creation=true

logging.level.vn.thathinh=DEBUG
