package vn.thathinh.constant;

public enum WebSocketMessageType {
    TOPIC_MESSAGE,
    FLIRT_MESSAGE,
    FLIRT_MATCHED,
    FLIRT_ENDED,
    FLIRT_CANCELLED,
    PRIVATE_MESSAGE,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    CONVERSATION_UPDATED,
    TOPIC_TYPING,
    TOPIC_PRESENCE,
    PRIVATE_TYPING,
    PRIVATE_READ,
    PRIVATE_MESSAGE_UPDATED,
    FLIRT_TYPING,
    FLIRT_MESSAGE_UPDATED,
    NOTIFICATION,
    EMAIL_VERIFIED
}
